### ISSUE TITLE
Plans to kill background apps by Google.

### ISSUE THREAD

**Issue by pY4x3g** [redPanda-project/redPandaj1.0#4]
Hi everyone,

we as a team decided to release our current unfinished work of our whitepaper as a draft and to cease our work until there are further information on the following topic:

There are new plans for Android in which Google wants to kill background processes. At this point, details about this plan are non-existent, but are believed to make a chat application like redPanda impossible to function properly.

Greets,
Robin

Whitepaper draft link: https://github.com/redPanda-project/redPandaj/blob/master/white-paper-draft.pdf

**Comment by cryptomarauder** [comment]
Why not develop the client in a portable way so it can be useful to more than just Android users? Android is turning into sh1t anyways so something better will come soon. Maybe write the backend in Python? Not too many ppl like running Java anyways. Python is so easy too. If not Python them check out Go. Should be portable.

**Comment by pY4x3g** [comment]
Our main goal was to deliver an application which can be used by everyone and therefore we targeted android, which requires/should be written in java.
It is an open-source project and you can start a python application if you wish :)

**Comment by pY4x3g** [comment]
Since we have new plans to develop the android and iOS app, this issue is closed. More information can be found in the readme.
